# Configurações do DQN
learning_rate: 0.00025
learning_starts: 5000
gamma: 0.97
batch_size: 128 # ver VRAM
buffer_size: 50000
num_stack: 4
frame_skip: 2
target_update: 10
max_episodes: 10000
max_grad_norm: 1.0

# Epsilon
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 100000 #50000

# Simulation
check_point: 100
video: 200

# Ambiente
game: "CarRacing-v3"
device: "cuda"
