# Configurações do DQN
learning_rate: 0.0001
gamma: 0.97
batch_size: 64
buffer_size: 50000
num_stack: 4
frame_skip: 2
target_update: 50
max_episodes: 5000
max_grad_norm: 1.0

# Epsilon
epsilon_start: 1.0
epsilon_end: 0.07
epsilon_decay: 100000 #50000

# Simulation
check_point: 100
video: 100

# Ambiente
game: "CarRacing-v3"
device: "cuda"
